### ISSUE TITLE
DigitizingTools causes QGis 3 to crash (on Mac)

### ISSUE THREAD

**Issue by dd-a** [bstroebl/DigitizingTools#28]
Whenever I simply try to activate the plugin by checking the activation box in the plugin manager QGis (3.0.2 from Kyngchaos) crashes immediately.  This affects versions 1.1 and 1.0.1 of the plugin on Mac OS Sierra (10.12.6).

**Comment by dd-a** [comment]
I just did, with the same result.  Is there any specific python library required by DigitizingTools that could be missing on my system ?

**Comment by bstroebl** [comment]
nope, furthermore in that case there should be an error report instead of a crash
Could you try with QGIS 3.0.3?

**Comment by dd-a** [comment]
As soon as it will be available I will and let you know.

**Comment by bstroebl** [comment]
I updated on Ubuntu this morning. But beware: I am not sure this will change anything, it is just a try

**Comment by bstroebl** [comment]
Maybe [this ](http://osgeo-org.1560.x6.nabble.com/QGIS-3-errors-after-install-on-macOS-10-13-4-td5365222.html)is related?

**Comment by dd-a** [comment]
I don't know.  This is exceeding my skills, but I don't have that error and the processing plugin loads correctly.

**Comment by dd-a** [comment]
Bad news : QGis 3.0.3 doesn't fix the issue.

**Comment by bstroebl** [comment]
There are issues pending for Win7 (#30) and Win 10 (#29). In Win 7 deactivating all other plugins made DigitizingTools loadable.
Which localization are you using?

**Comment by dd-a** [comment]
I tried this morning and it crashed the same.

**Comment by bstroebl** [comment]
It may be possible that the Qgis2threejs plugin causes the issue. Please try if unlaoding Qgis2threejs solves the problem.

**Comment by dd-a** [comment]
Nope, it was not even installed.

**Comment by bstroebl** [comment]
So to sum things up: QGIS crashes when you try to load the plugin, no matter if any other plugin is loaded or not.
Please try the new version 1.1.1 of the plugin and check if it soves the issue.

**Comment by dd-a** [comment]
That's exactly what's happening and unfortunately version 1.1.1 did not solve the issue.

**Comment by bstroebl** [comment]
Thank you for trying, nevertheless. I am sorry to read 1.1.1 is not better (I fixed an issue that randomly gave me a runtime error). But I have no possibility to reproduce this problem on a Mac.

**Comment by dd-a** [comment]
I understand.  Just ask, If you have another idea some day.

**Comment by bstroebl** [comment]
My idea would be to stay tuned and retry with any new major version of QGIS. Would be great to get feedback once the problem is solved. I leave this ticket open until then.

**Comment by dd-a** [comment]
Just to inform you that nothing has changed with QGis 3.2 and version 1.1.5 (and Mac OS 10.13.6).  Still crashing.

**Comment by bstroebl** [comment]
@xsaiama 
This has already been [reported](https://github.com/bstroebl/DigitizingTools/issues/30) and (partly) solved. This thread is on MAC, if you have new information on Win7 please report it in the other thread.

**Comment by xsaiama** [comment]
Sorry.

Can you delete my message, since it is not useful in this thread?
I can not wait to use the essential DigitizingTools in Qgis 3.XX.
In the meantime, I'm using Qgis 2.18.

Regards,

________________________________
Marc-André Saia
Cartographe – Direction générale

Communauté métropolitaine de Montréal
1002, rue Sherbrooke Ouest, bureau 2400
Montréal (Québec) H3A 3L6
[cid:image001.jpg@01D41DAB.707C6280] (514) 350-2583
[cid:image002.jpg@01D41DAB.707C6280] (514) 350-2599

AVIS DE CONFIDENTIALITÉ
Ce courriel est strictement réservé à l'usage de la personne à qui il est destiné et peut contenir de l'information privilégiée ou confidentielle. Si vous avez reçu ce courriel par erreur, veuillez nous en aviser immédiatement et le supprimer de votre système informatique sans en tirer de copies.
Avant d'imprimer, pensez à l'environnement ! [cid:image003.jpg@01D41DAB.707C6280]

De : Bernhard Ströbl [mailto:notifications@github.com]
Envoyé : 16 juillet 2018 09:34
À : bstroebl/DigitizingTools
Cc : Marc-André Saia; Mention
Objet : Re: [bstroebl/DigitizingTools] DigitizingTools causes QGis 3 to crash (on Mac) (#28)


@xsaiama<https://github.com/xsaiama>
This has already been reported<https://github.com/bstroebl/DigitizingTools/issues/30> and (partly) solved. This thread is on MAC, if you have new information on Win7 please report it in the other thread.

**Comment by bstroebl** [comment]
Does deactivating Qgis2threejs help in your case?

**Comment by xsaiama** [comment]
I uninstalled all the plugins and then installed Digitizing Tools.
It works now. I then reinstalled the other plugins one by one except Qgis2threejs then it's still going.

Thank you.

**Comment by bstroebl** [comment]
Hi Fernando,
sorry for the late reply, I had been on holidays.
This thread is on the plugin crashing QGIS on Mac, anyways, I never had any problems (except the Qgis2threejs thing) on Ubuntu 16.04 (Gnome). My first advice would still be to **deactivate all other plugins** and then restart QGIS and retry loading DigitizingTools.
Please see this [QGIS webpage](https://www.qgis.org/en/site/getinvolved/development/bugreporting.html) on creating more helpful messages (no guarantee I can make anything useful out of it).

**Comment by FernandoRoxo** [comment]
Hi Bernard,

I am afraid to be kind of hijacking the Mac thread on the subject, the point is that was the closest issue I fount to report my problem.

I have followed your suggestion and just deactivated all other plugins and, as expected, the digitizing plugin came up without crashing Qgis.  Then I started to reactivate the others plugins and deactivated and reactivated the digitizing plugin.    With  the digitizing plugin activated, there were two plugins that I was able to activate (OSM Tools and Qgis2threejs) and after that I could deactivate the digitizing plugin but upon reactivating the Qgis crashed.     With all the others I have installed no problem showed up.

I have Qgis 3.2.1-Bonn installed from the Qgis stable repositiry on [Xu|U]buntu 18.04 LTS.    To be absolutely honest, it is not a new installation, I had a 16.04 LTS upgraded to 18.04 LTS, so it is possible that some remaining from the previous version can be playing in the shadows.

Please, let me know it I can provide any more info that could help in any way.

============================================
From Qgis about:

QGIS version                               | 3.2.1-Bonn               | QGIS code revision | 1edf372
--                                                     | --                                | --                                  | --
Compiled against Qt                   | 5.9.5                         |
Running against Qt                     | 5.9.5
Compiled against GDAL/OGR |   2.2.3                        | 
Running against GDAL/OGR   |   2.2.3
Compiled against GEOS           | 3.6.2-CAPI-1.10.2  | 
Running against GEOS             |  3.6.2-CAPI-1.10.2 4d2925d6
PostgreSQL Client Version       | 10.3 (Ubuntu 10.3-1) | 
SpatiaLite Version                       | 4.3.0a
QWT Version                               | 6.1.3 | 
QScintilla2 Version                     | 2.10.2
PROJ.4 Version                           | 493

**Comment by bstroebl** [comment]
I am running Ubuntu 16.04 which has an older Qt (5.5.1) than yours. Maybe that's why loading _OSM Tools_ and DigitizingTools in parallel is working for me. 
All I can do is to advice you to not use the plugins at the same time. This is definitely annoying but the cause at least in case of _QGIS2threejs_ is the other plugin and not DigitizingTools (see the [issue ](https://github.com/minorua/Qgis2threejs/issues/134) I opened there).
No idea if _OSM Tools_ is similar, though.

**Comment by dd-a** [comment]
Hello Bernard,
I also found that go2streetview in parallel with  Digitizing Tools causes the crash of QGis (3.2.0).  I just made a brand new install of my system and installed the QGis extensions one by one and testing the activation of DT each time.  Not only must the other one be de-activated, it must also be uninstalled and QGis restarted.

**Comment by FernandoRoxo** [comment]
I don't know the system dd-a above is using and I don't need the go2streetview plugin, but just in order to tray to gather as much information as possible, I have installed this plugin and I can confirm that in [Xu|U]buntu 18.04 and Qgis 3.2.1 if I disable the DigitizingTools and enable in sequence, the Qgis crashes.

HTH
